### PR TITLE
Fix bug hiding DRATs failures on long running environments

### PR DESCRIPTION
**Pull request by bruce-ricard**
After chatting with Jake this morning we agreed I'd make this PR to improve the routing test suite.

Currently, if your routing groups DRATs fail and leave the routing group in the environment, and that environment in long lasting, subsequent DRATs will succeed even if the restore doesn't work because it's not testing the right thing.

This PR ensures that we are indeed making sure that we are searching for a routing group that did NOT exist before the backup.

### CODE REVIEW

**Comment by bruce-ricard** [comment]
> EasyCLA — Missing CLA Authorization.

Why is it asking me this? I'm member of CF org :(

**Comment by totherme** [comment]
I see that this failed our CI: https://backup-and-restore.ci.cf-app.com/teams/main/pipelines/drats/jobs/run-drats-prs/builds/231

I believe you already have permission to view the full CI output (and actually to merge this PR once the tests pass). Do you need help debugging the failure, or is this an easy fix?

**Comment by bruce-ricard** [comment]
> I see that this failed our CI: https://backup-and-restore.ci.cf-app.com/teams/main/pipelines/drats/jobs/run-drats-prs/builds/231
> 
> I believe you already have permission to view the full CI output (and actually to merge this PR once the tests pass). Do you need help debugging the failure, or is this an easy fix?

Hmm I did run the DRATs on my own pipeline, pointing it at this PR's branch, and they passed. I'll take a look.

**Comment by bruce-ricard** [comment]
I am able to sorta reproduce, but I'm getting a different error message:

>   Expected success, but got an error:
      <routing_api.Error>: {
          Type: "ResponseError",
          Message: "",
      }
      

I'm not getting any message in my error for some reason. I have located which commit created the error. It looks like the test doesn't like it when I try to delete router groups. I'm not sure why. The message suggests that the routing API doesn't support this method, but why is it in the client interface then? 🤷‍♂

**Comment by totherme** [comment]
Ok, maybe the issue is a versioning one. One of our team noticed today that our CF-Deployment is a little old. We can play our chore to update it ( https://www.pivotaltracker.com/story/show/171100619 ) and see if that fixes the pipeline.

If that *does* fix the pipeline, then it suggests that drats might only work with particular versions of CF. If that's the case, we might need to check what versions we ought to be supporting, and see if there's any extra work to do.

**Comment by bruce-ricard** [comment]
@totherme We believe we fixed the build and the tests, but we can't restart them on your pipeline. Could you restart the job with the updated commits please?

**Comment by totherme** [comment]
I'm surprised you don't have the power to start the pipeline... Folks in the github `cloudfoundry-incubator:cf-networking` team should have `pipeline-operator` privileges.

In any case, I've started the pipeline now.

**Comment by totherme** [comment]
GREEN!

**Pull request merged**
