### PR TITLE
Fix issues with the NFS broker testcase

### PR DESCRIPTION
**Pull request by davewalter**
Hi,

This PR updates the NFS broker testcase to use the presence of the NFS broker password to determine whether or not to register a service broker, instead of the username, to match existing logic in `run_acceptance_tests_with_bbl_env.sh`. It also updates the `credhub-compatible/update-integration-config` CI task to add support for an optional parameter to include the NFS broker testcase, which is needed now that the test case has been disabled by default.

[#159975576](https://www.pivotaltracker.com/story/show/159975576)

Please let me know if you have any questions.

Dave

### CODE REVIEW

**Comment by davewalter** [comment]
I'm on the fence about switching from using the presence/absence of the nfs broker password to determine whether or not to run the test case to using a CI task param, so please let me know what you think.

**Comment by davewalter** [comment]
Please hold off on merging this. I may need to make a change.

**Comment by davewalter** [comment]
I think this is good to go now. It's passing in our CI.

**Comment by davewalter** [comment]
I suspect that this failed because the broker is not currently being registered by the nfsbrokerpush errand (we have an [open PR](https://github.com/cloudfoundry/cf-deployment/pull/592) for this with cf-deployment that is blocked on us having DRATs test coverage), so you will need to set the `NFS_CREATE_SERVICE_BROKER` param to get the tests to pass. Once the PR is merged and the change has been merged to master, you will be able to remove this param again.

I'll check in with y'all tomorrow and could x-team pair if that would help.

**Comment by MirahImage** [comment]
Hi @davewalter 

Thank you for this PR. CI failed because we use a separate `integration_config.json` in our CI than the one in the DRATS repo. We have added `"nfs_create_service_broker": true` and have retriggered the job.

We don't think the `update-integration-config` task needs to handle `INCLUDE_NFS_BROKER_TESTCASE` and `NFS_CREATE_SERVICE_BROKER`. Instead the corresponding flags should be set in the integration config passed to the task via `INTEGRATION_CONFIG_FILE_PATH`. The main responsibility of the `update-integration-config` task is to populate credentials. Please could you remove those env vars from the task?

Also, we have issued a deprecation notice for the use of env vars as a means to configure DRATS in favour of using integration config only. So please could you remove support for `NFS_CREATE_SERVICE_BROKER` from the `drats` CI task and `env.go`?

Best wishes
Mirah and @jamesjoshuahill

**Comment by davewalter** [comment]
Hi @MirahImage 

> We don't think the update-integration-config task needs to handle INCLUDE_NFS_BROKER_TESTCASE and NFS_CREATE_SERVICE_BROKER. Instead the corresponding flags should be set in the integration config passed to the task via INTEGRATION_CONFIG_FILE_PATH. The main responsibility of the update-integration-config task is to populate credentials. Please could you remove those env vars from the task?

Fair enough. The name of the `update-integration-config` task made it seem like it was acceptable for it to do more than just injecting credentials. I was also attempting to clean up [existing logic](https://github.com/cloudfoundry-incubator/disaster-recovery-acceptance-tests/blob/059b5c3755fb3b756c76779c76ba0890a2b1c058/ci/credhub-compatible/update-integration-config/task.sh#L62-L64) in that task that set the `include-cf_nfsbroker` flag based on the presence/absence of an NFS broker password. I have instead removed that logic completely.

I have been trying to use as much of the setup/tooling in the DRATs repo as possible to reduce the tooling that we had to maintain, but perhaps that isn't the correct approach. Do you have any plans to offer a generic task that will allow users to set flags in the `integration-config.json`, or are the CI tasks in DRATs not intended for external use? Also, given that you don't use the `integration-config.json` in DRATs in your own CI, perhaps it should be deleted in favour of the example in the README? That would eliminate the temptation for people to try to use it.

At this point, the only two places where the `INCLUDE_NFS_BROKER_TESTCASE` and `NFS_CREATE_SERVICE_BROKER` environment variables are mentioned is in the `run_acceptance_tests_with_bbl_env.sh` and the README. Given that it sounds like you are also deprecating the scripts that use/manipulate environment variables in favour of `run_acceptance_tests_local_with_config.sh`, should I remove them completely?

> Also, we have issued a deprecation notice for the use of env vars as a means to configure DRATS in favour of using integration config only. So please could you remove support for NFS_CREATE_SERVICE_BROKER from the drats CI task and env.go?

Sounds good.

Let me know if you have more questions/concerns.

Regards,
Dave

**Comment by MirahImage** [comment]
Thank you @davewalter!

We agree that `ci/integration-config.json` should be deleted to avoid confusion in favour of the copy in README.

When we deprecate environment variables we'll review the scripts as well so that they all use integration config.

Best wishes
Mirah and @jamesjoshuahill

**Pull request merged**
