### PR TITLE
Add a test case for samba service broker

### PR DESCRIPTION
**Pull request by Kaixiang**
[#151415093](https://www.pivotaltracker.com/story/show/151415093)

See below.

## Checklist

Please provide the following information:

- [X] What component are you testing?

* we are testing Samba service broker [here](https://github.com/cloudfoundry/smb-volume-release).

- [X] Have you created a TestCase and added it to the list of cases to be run?

* Yes, and we made it optional for deployments doesn't contains smb broker.

- [X] Have you manually validated your TestCase against a deployed Cloud Foundry? If so, which version?

* Yes, it passed our pipeline with latest cf [here](http://persi.ci.cf-app.com/teams/main/pipelines/persi/jobs/pats-drats/builds/79)
we continue deploy and run drats test when there is new cf available.

- [X] Does this change rely on a particular version of CF release?

* No

- [X] Are you available for a cross-team pair to help troubleshoot your PR?

* Yes

- [X] Have you submitted a pull request to modify the cf-deployment [backup and restore opsfile](https://github.com/cloudfoundry/cf-deployment/blob/master/operations/experimental/enable-backup-restore.yml) to add a backup job and properties where appropriate?

* Not yet, this release is still not yet released to bosh io and we have a story in icebox to do the PR after that.

### Do you have any other useful information for us?

We're on the #bbr cloudfoundry Slack channel if you need us.

### CODE REVIEW

**Comment by julian-hj** [comment]
Hi folks,

It would be awesome to have some kind of feedback on this PR.  Are y'all planning to merge it, or should we be making alternate plans to run drats tests for the Samba broker?

Thanks!

**Comment by MirahImage** [comment]
Hi, 

Sorry for the very long delay. Looking at the ci failure, it seems the code to determine whether to run the SMB service broker test is failing to properly skip the test 
https://github.com/cloudfoundry-incubator/disaster-recovery-acceptance-tests/pull/20/commits/a13183b893aabd70d693b7da5e6ac43cb9292c72#diff-a541857653720144737034f1c5959cf5

Hopefully this isn't too much trouble to fix. 

Cheers,
Mirah

**Comment by gcapizzi** [comment]
Hi @Kaixiang! This is still failing on our CI because we still haven't managed to deploy a CF environment with SMB enabled. This is a bit tricky because we're using the [`cf-deployment-concourse-tasks`](https://github.com/cloudfoundry/cf-deployment-concourse-tasks) which only support one `ops-files` input, which in our case is `cf-deployment`. Do you plan to have your opsfile include in `cf-deployment` any soon?

**Comment by julian-hj** [comment]
Hi @gcapizzi, we don't have immediate plans to PR the smb ops files into cf-deployment, but it is pretty straightforward to aggregate ops files from multiple repos into the same directory as a preparatory step in your pipeline using the `collect-ops-files` task.  Here's where we do that in our pipeline: https://github.com/cloudfoundry/persi-ci/blob/master/persi.yml#L2381

(We collect ops files from several different repos.  It sounds like your case will be considerably more straightforward.)

**Comment by gcapizzi** [comment]
> it is pretty straightforward to aggregate ops files from multiple repos into the same directory as a preparatory step in your pipeline using the collect-ops-files task

Ouch, I'd forgot about that task! We'll try it ASAP and see if we can get this test to pass 🙂 thanks!

**Comment by ChunyiLyu** [comment]
Hi @julian-hj && @Kaixiang, after discussing with the team, we decided not to proceed with the PR since the component is not integrated into cf-deployment yet. Sorry for all of the backup and forth. I will close the PR for now, and feel free to reopen it in the future when it is integrated into cf-deployment.

Cheers,
Chunyi

**Pull request closed without merging**
