### PR TITLE
Add nfsbroker tests

### PR DESCRIPTION
**Pull request by paulcwarren**
[#151027702](https://www.pivotaltracker.com/story/show/151027702)

Thanks for submitting a PR to DRATS.

- [ ] What component are you testing?
nfs broker backup and restore

- [ ] Have you created a TestCase and added it to the list of cases to be run?
Yes

- [ ] Have you manually validated your TestCase against a deployed Cloud Foundry? If so, which version?
We are running this new test in our pipeline against cf release-candiate and diego develop branches

- [ ] Does this change rely on a particular version of CF release?
Has to include CAPIs bbr implementation

- [ ] Are you available for a cross-team pair to help troubleshoot your PR?
Sure

- [ ] Have you submitted a pull request to modify the cf-deployment [backup and restore opsfile](https://github.com/cloudfoundry/cf-deployment/blob/master/operations/experimental/enable-backup-restore.yml) to add a backup job and properties where appropriate?
No we haven't.  NFS is optional in cf-deployment so what we have done is this PR instead.

### Do you have any other useful information for us?

We're on the #bbr cloudfoundry Slack channel if you need us.

### CODE REVIEW

**Comment by julian-hj** [comment]
Just a note on this--I can't actually see the build failure but I'd wager that it's due to your cf-deployment not having the required ops files to turn on volume services.

Those have been sitting in a PR to cf-deployment for quite some time now: https://github.com/cloudfoundry/cf-deployment/pull/230

So, feel free to harass the rel-int team to get them to accept that PR, or, if you are in a hurry (I think you are in a hurry) you can also pick up the ops files we use in our own pipelines:
https://github.com/cloudfoundry/persi-ci/blob/master/operations/enable-nfs-volume-service.yml
https://github.com/cloudfoundry/persi-ci/blob/master/operations/enable-nfs-broker-backup.yml

HTH,
-Julian

**Comment by edwardecook** [comment]
Hi @julian-hj thanks for pointing us in the right direction wrt ops files, it looks like the opsfiles PR'd by you to cf-deployment are slightly out of date compared to the ones in your ci repo (this commit doesn't have an equivalent: https://github.com/cloudfoundry/persi-ci/commit/d01244c9bb48c4546fe87e574e00b7b0e5255132)

**Comment by edwardecook** [comment]
Hi @julian-hj @paulcwarren this is currently failing in CI due to your new testcase requiring a bunch of environment variables to be specified: https://github.com/paulcwarren/disaster-recovery-acceptance-tests/blob/d975c36a519ecaa548ae4eafc127f2007f61612c/testcases/nfs_testcase.go#L38-L40

1. Could you let us know what values we should use for those environment variables in our CI pipeline?

1. For each environment variable, could you add a corresponding property to the CloudFoundryConfig struct - see https://github.com/cloudfoundry-incubator/disaster-recovery-acceptance-tests/pull/9 for a similar change. Also could you then set this property as with existing properties here: https://github.com/cloudfoundry-incubator/disaster-recovery-acceptance-tests/blob/master/acceptance_test.go#L21-L26 - this means the environment is only queried at the beginning of the test suite, and means we fail fast and with clear failure messages when the environment is wrongly configured.

Thanks!

**Comment by julian-hj** [comment]
regarding the PR--it is true, we PR'd this stuff a while back, and it's taking them quite some time to get around to merging it.  If/when they do, we'll update the PR.

**Comment by julian-hj** [comment]
@edwardecook regarding #2 above, would you also like us to update ci/task and ci/task.yml to add the new properties with usable defaults?  I am not sure how these get set in your pipeline.  In ours, most are set by default values, except for the broker password, which we extract from deployment-vars in script.

**Comment by flangewad** [comment]
Hi @julian-hj thanks for the above. We can now run the test case on our environment successfully! This should all be fine, so we'll close this PR soon (we have merged in the code via another route)

**Comment by flangewad** [comment]
Hi @paulcwarren and @julian-hj -- we've got this running against our main pipeline on master with a few small changes. Green CI run is here: https://backup-and-restore.ci.cf-app.com/teams/main/pipelines/drats/jobs/run-drats/builds/56

Closing this PR.

**Comment by julian-hj** [comment]
Excellent! Please let us know if you require anything else.  Probably once rel-int accepts our PR to add nfs related ops files to cf-deployment, you will want to switch over to use those ones instead of the ones in presi-ci, but we will coordinate with Theresa when that happens.

**Pull request closed without merging**
