### PR TITLE
Adds the router group testcases.

### PR DESCRIPTION
**Pull request by flawedmatrix**
We would like to add the test case for backing up and restoring router groups for the Routing API.

We tested this against the latest release-candidate of CF deployment, but it shouldn't rely on any particular version of CF release. We only require that routing release be 0.164.0 or after, and that the `bbr_routing` job is colocated with the `api` instance group.

If there is any issue with this PR please let us know here or on the CloudFoundry Slack at the #routing channel.

Thanks,
Edwin

Thanks for submitting a PR to DRATS.

## Checklist

Please provide the following information:

- [x] What component are you testing?
- [x] Have you created a TestCase and added it to the list of cases to be run?
- [x] Have you manually validated your TestCase against a deployed Cloud Foundry? If so, which version?
- [x] Does this change rely on a particular version of CF release?
- [x] Are you available for a cross-team pair to help troubleshoot your PR?

### Do you have any other useful information for us?

We're on the #pcf-backup-restore Slack channel if you need us.

### CODE REVIEW

**Comment by ChunyiLyu** [comment]
Hi @flawedmatrix, I saw the commit which adds the `bbr-routing` job on develop branch, but not on tag `v0.164`. Will `bbr-routing` job be included in the next routing-release?

Thanks,
Chunyi

**Comment by flawedmatrix** [comment]
Hi @ChunyiLyu, I made a mistake in saying 0.164.0. Our bbr commits have not made it to a final release of routing yet. They should be included in the next-routing-release.

Thanks,
Edwin

**Comment by aaronshurley** [comment]
We have updated our PR. We made some changes to our bbr-routing jobs so the next final release, 0.166.0, will include those changes. Here's a link to track our release marker:  https://www.pivotaltracker.com/story/show/152248158

**Comment by edwardecook** [comment]
Hi @flawedmatrix @aaronshurley the reason for the current ci failure seems to be down to your (PR into cf-deployment)[https://github.com/cloudfoundry/cf-deployment/pull/311] not having been merged in. This means that your backup and restore scripts aren't running as they aren't on our test deployment. Hence your assertions about router_groups fail. Which is a good validation of your test cases :)
cc @flangewad

**Pull request merged**
