### PR TITLE
Add DRATS test case for UAA backup/restore

### PR DESCRIPTION
**Pull request by fhanik**
UAA with BBR Support is out in [v52](http://bosh.io/releases/github.com/cloudfoundry/uaa-release?version=52)

Reference: https://www.pivotaltracker.com/story/show/151624690

Thanks for submitting a PR to DRATS.

1. Testing: UAA
1. Added testcase
1. Validated against: cf-deployment/develop on this day. bbr opsfile modified to colocate [`bbr-uaadb`](https://github.com/cloudfoundry/uaa-release/tree/develop/jobs) job from `uaa-release`
1. Yes, this PR relies on functionality not yet released. This PR will be updated when it is.

## Checklist

Please provide the following information:

- [x] What component are you testing?
- [x] Have you created a TestCase and added it to the list of cases to be run?
- [x] Have you manually validated your TestCase against a deployed Cloud Foundry? If so, which version?
- [x] Does this change rely on a particular version of CF release?
- [x] Are you available for a cross-team pair to help troubleshoot your PR?

### Do you have any other useful information for us?
The [`testsuite`](https://github.com/cloudfoundry-incubator/disaster-recovery-acceptance-tests/blob/402dfad4b437ea43b021ed89405f968b6a5ceb44/testcases/testcase_helper.go#L6-L9) is not really a suite. If the first test fails, the other tests in the suite are not run. 
This delays the feedback loop for failed tests. Adding `-keepGoing` to ginkgo did not solve that problem.

The test suite itself does not document what additional steps are required to make cf-deployment pass. An opsfile should be referenced.

UAA adds the `bbr-uaadb` job to the backup-and-restore-sdk VM
```
      jobs:
      - name: bbr-uaadb
        release: uaa
      - name: database-backup-restorer
        release: backup-and-restore-sdk
```

We're on the #pcf-backup-restore Slack channel if you need us.

### CODE REVIEW

**Comment by tinygrasshopper** [comment]
@fhanik we cant merge this yet, as its not passing against cf-deployment yet. Can you please update https://www.pivotaltracker.com/story/show/151695510 with the story in your backlog to bump uaa on cf-deployment? We can merge it then. 

The test itself looks good

cc: @gcapizzi

**Comment by fhanik** [comment]
cf-release has been bumped with [uaa-release/v52](http://bosh.io/releases/github.com/cloudfoundry/uaa-release?version=52)

**Comment by fhanik** [comment]
@tinygrasshopper it's not so much the name, it is how the life cycle is handled. in our case, we had to comment out other tests, because if they failed, our test wouldn't even run.

ie, we believe they should be treated as test cases, and all of them should run regardless of success or failure from a previous test.

**Comment by aashah** [comment]
What branch of cf-deployment does our updated uaa-release need to be on? It's on the `develop` branch of cf-deployment currently.

**Pull request merged**
