### PR TITLE
Wip networking drats

### PR DESCRIPTION
**Pull request by joachimvaldez**

### CODE REVIEW

**Comment by joachimvaldez** [comment]
Forgot to put story #149612263

It seems we want our test case in this cloudfoundry-incubator repo, but we will run only our test case in CI.

**Comment by tinygrasshopper** [comment]
hi @joachimvaldez, we are getting failures when we run the DRATs PR against cf-deployment master. Are changes in this PR complete and mergeable?

**Comment by joachimvaldez** [comment]
Hey @tinygrasshopper . My guess would be that you need to turn on the [`bbr-cfnetworkingdb.release_level_backup`](https://bosh.io/jobs/bbr-cfnetworkingdb?source=github.com/cloudfoundry/cf-networking-release) property. We currently run this test in our pipeline with a MySQL database. If you want, I can send you our manifest for the deployment.

**Comment by tinygrasshopper** [comment]
hi @joachimvaldez, we are running drats against a cf-deployment/develop which has that flag enabled(https://github.com/cloudfoundry/cf-deployment/blob/develop/operations/experimental/enable-backup-restore.yml#L57-L59) which cf-deployment are you running your ci against?

**Comment by tinygrasshopper** [comment]
@joachimvaldez we are getting this failure:
```
backing up Cloud Foundry
/tmp/build/1f5f819e/src/github.com/cloudfoundry-incubator/disaster-recovery-acceptance-tests/acceptance_test.go:13
  backups and restores a cf [It]
  /tmp/build/1f5f819e/src/github.com/cloudfoundry-incubator/disaster-recovery-acceptance-tests/runner/runner.go:27

  Expected
      <int>: 1
  to match exit code:
      <int>: 0

  /tmp/build/1f5f819e/src/github.com/cloudfoundry-incubator/disaster-recovery-acceptance-tests/common/command_line_helpers.go:20

  Full Stack Trace
  	/tmp/build/1f5f819e/src/github.com/cloudfoundry-incubator/disaster-recovery-acceptance-tests/vendor/github.com/onsi/gomega/internal/assertion/assertion.go:69 +0x1ef
  github.com/cloudfoundry-incubator/disaster-recovery-acceptance-tests/vendor/github.com/onsi/gomega/internal/assertion.(*Assertion).To(0xc4215ab680, 0x9e9040, 0xc421716de0, 0x0, 0x0, 0x0, 0xc4215ab680)
  	/tmp/build/1f5f819e/src/github.com/cloudfoundry-incubator/disaster-recovery-acceptance-tests/vendor/github.com/onsi/gomega/internal/assertion/assertion.go:35 +0xae
  github.com/cloudfoundry-incubator/disaster-recovery-acceptance-tests/common.RunCommandSuccessfully(0xc420259cb0, 0x85, 0x0, 0x0, 0x0, 0xc420259cb0)
  	/tmp/build/1f5f819e/src/github.com/cloudfoundry-incubator/disaster-recovery-acceptance-tests/common/command_line_helpers.go:20 +0x155
  github.com/cloudfoundry-incubator/disaster-recovery-acceptance-tests/testcases.(*CfNetworkingTestCase).AfterBackup(0xc420058dd0, 0xc4200160d3, 0x2, 0xc42001400b, 0x22, 0xc4200160b2, 0x5, 0xc4200140d2, 0x14, 0xc4200160d3, ...)
  	/tmp/build/1f5f819e/src/github.com/cloudfoundry-incubator/disaster-recovery-acceptance-tests/testcases/cf_networking_testcase.go:36 +0x1b5
  github.com/cloudfoundry-incubator/disaster-recovery-acceptance-tests/runner.RunDisasterRecoveryAcceptanceTests.func2()
  	/tmp/build/1f5f819e/src/github.com/cloudfoundry-incubator/disaster-recovery-acceptance-tests/runner/runner.go:52 +0x5f4
  github.com/cloudfoundry-incubator/disaster-recovery-acceptance-tests/vendor/github.com/onsi/ginkgo/internal/leafnodes.(*runner).runSync(0xc4200105a0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
  	/tmp/build/1f5f819e/src/github.com/cloudfoundry-incubator/disaster-recovery-acceptance-tests/acceptance_suite_test.go:12 +0x64
  testing.tRunner(0xc4201820f0, 0x811428)
  	/usr/local/go/src/testing/testing.go:746 +0xd0
  created by testing.(*T).Run
  	/usr/local/go/src/testing/testing.go:789 +0x2de
  
------------------------------


Summarizing 1 Failure:

[Fail] backing up Cloud Foundry [It] backups and restores a cf 
/tmp/build/1f5f819e/src/github.com/cloudfoundry-incubator/disaster-recovery-acceptance-tests/common/command_line_helpers.go:20

Ran 1 of 1 Specs in 521.912 seconds
FAIL! -- 0 Passed | 1 Failed | 0 Pending | 0 Skipped --- FAIL: TestPcfBackupAndRestoreAcceptanceTests (521.91s)
FAIL
```

It seems it cant delete the network policy post backup

**Comment by joachimvaldez** [comment]
Hey @tinygrasshopper I think I know the issue. There's test pollution from the other two `AfterBackup`s being called. Our `AfterBackup` needs to `cf target` the right `org`/`space` after the other `AfterBackup`s  from the other two test cases get called. I'll retry on our environment with the other two test cases and see if I can duplicate this. (We've actually been skipping the other two test cases in our environment, so that's why we never saw this error). I'll add this fix to the PR.

Unfortunately I'm OOO the rest of this week, but I'll comment back here before I leave.

**Comment by joachimvaldez** [comment]
Btw we're running from `cf-deployment/release-candidate`

**Comment by joachimvaldez** [comment]
I'm running into this error where the cloud_controller_ng pre-backup-lock script fails:
```
pre-backup-lock script for job cloud_controller_ng failed on api/7e97375d-c1bf-4eed-a94b-6a37a0ca8b40.
Stdout: 0
Endpoint https://api.mitre.c2c.cf-app.com/ did not go down after 60 seconds
```
Also, I did not enable `bbr-uaadb` because I noticed we were running uaa release 51 on our deployment. It looks like 52 just made it to cf-deployment/release-candidate.

I'm OOO after today, so feel free to message the team on Slack.

**Comment by tinygrasshopper** [comment]
@joachimvaldez there is a flake in the CAPI scripts (which is currently being solved by https://www.pivotaltracker.com/story/show/151817365). I think it makes sense to merge this PR as it passes on our CI.

**Pull request merged**
