### PR TITLE
Embed fixtures to fix package import issue

### PR DESCRIPTION
**Pull request by crhntr**
Note from now on changes to the fixtures app will
require running `go generate`.

The problem with the current implementation is we expect when
this package is imported by another project using go modules,
that all the files are stored in the module cache. This does
not seem to be true for embedded modules, most notably
credhub-test-app. By embedding archived versions of the fixtures
we get around this issue. Simply embedding the directories
like `//go:embed credhub-test-app test_app` did not work
and returned a build time error like this:
   golang cannot embed directory $DIR: in different module

I don't really like how I implemented this fix because it adds an
additional step and could easily be missed when making changes
to the fixtures; however, I tried a few other approaches and this
one seemed the cleanest. I would not be opposed to using a
Makefile instead of `go generate` because it would be more
discoverable to contributors.

A/C:
Given the testcases or runner package are imported into a
      different module
When some specific fixture needs to be used
Then the fixture is written to a provided temporary directory

I tested this with a smith environment and the acceptance tests
are not passing yet.

Thanks for submitting a PR to DRATs.

## Checklist

Please provide the following information (and links if possible):

### [ ] Have you added any new properties/information to all of the following:
* [ ] [integration_config.json](../ci/integration_config.json): Specifically, an `include_<testcase-name>` property
* [ ] [documentation in docs/](../docs/)
* [ ] [tasks in ci/](../ci/)
* [ ] [scripts in scripts/](../scripts/)

## Do you have any other useful information for us?

We're on the #bbr cloudfoundry Slack channel if you need us.

### CODE REVIEW

**Comment by dlresende** [comment]
Hi @crhntr.

I had started putting together a PR to address the credhub app usage in `p-drats`. I took the time to finish it today: #108

Now I guess we have 2 solutions to fix this issue.

Let me know what do you think.

FYTI, the `p-drats` pipeline went green on our side with #108

**Comment by crhntr** [comment]
Hello @dlresende, I responded on the p-drats issue. In short, #108 will probably work. I'll integrate it and let you know. Thank you!

One positive of the approach of #107 is it is backwards compatible from a pipeline config perspective (you don't need to get and configure drats in packages importing it) but a negative is #107 changes the package API to use `WriteFixturesToTemporaryDirectory` instead of `CurrentTestDir`. Feel free to go with whatever you think is best. If you decide you'd prefer to keep package (over pipeline config) compatibility, feel free to close this without merging.

**Comment by crhntr** [comment]
I just tried to add the drats repo to our pipeline to pass it in like you did in your CI but I ran across a potential issue.

With the implementation in #108, there is a chance the drats resource and imported module will get out of sync. This issue would be kind of hard to diagnose.

**Comment by dlresende** [comment]
Hi @crhntr. Your last point about the module and the resource going async is fair. Although on our side as pipelines are reacting to new changes instantly, I don't see this occurring very often.

**Comment by dlresende** [comment]
Hi @crhntr. Is this work still something y'all want to invest in or should we close this PR?

**Comment by dlresende** [comment]
Hi @crhntr. I'll close this PR for now. Let us know if you want to reopen and push this further.

**Pull request closed without merging**
