### PR TITLE
Update drats to use new credhub permissions model

### PR DESCRIPTION
**Pull request by athornton2012**
- Ensure that the credhub fixture app has permission to create
credentials
- Ensure that the credential created by the credhub fixture app is not
tied to the instance guid
- Update the ci task to require a client and client secret that have
credhub write_acl permissions

Signed-off-by: Chhavi Kankaria <ckankaria@pivotal.io>

## Checklist

- [X] What component are you testing?
Runtime CredHub

- [X] Have you created a `TestCase` and added it to the list of cases to be run?
We modified an existing test case

- [X] Have you added an `include_<testcase-name>` property and any other new properties to the sample integration_config.json? We modified the ci task to include the credhub admin client name and client secret.

- [X] Have you manually validated your `TestCase` against a deployed Cloud Foundry? If so, which version? we have validated against cf-deployment (waiting for branch to be merged https://github.com/cloudfoundry/cf-deployment/pull/580)

- [X] Does this change rely on a particular version of CF release?
This change relies on a version of cf-deployment in which https://github.com/cloudfoundry/cf-deployment/pull/580 is merged. 

- [X] Are you available for a cross-team pair to help troubleshoot your PR?
Yes.

- [X] Have you submitted a pull request to modify the cf-deployment [backup and restore opsfile](https://github.com/cloudfoundry/cf-deployment/blob/master/operations/experimental/enable-backup-restore.yml) to add a backup job and properties where appropriate? 
Yes https://github.com/cloudfoundry/cf-deployment/pull/580

### CODE REVIEW

**Comment by ChunyiLyu** [comment]
Hi @athornton2012, we are wondering whether we can successfully run the updated credhub testcase against PAS? Will the credhub test case become incompatible with versions of PAS?

The reason I am asking this is that our team also maintains the pivotal-disaster-recovery-acceptance-tests repo, which runs all the open-sourced test cases in drats, and some other close-sourced components test cases. Different from drats, which only needs to be compatible with cf-deployment master , our team, and the releng team run pivotal-disaster-recovery-acceptance-tests against different versions of PAS (from 1.11 to latest).

**Comment by ljfranklin** [comment]
@ChunyiLyu PAS 2.4 will contain credhub 2.0, the 2.3 release we're working on now will not. @athornton2012 could this PR be written in a way that's compatible with either 2.0 Credhub or pre-2.0 Credhub?

**Comment by chhhavi** [comment]
@ljfranklin Do you want to write this in a way where it's compatible with both PAS 2.3 and but also the latest cf deployment which has CredHub 2.0?

**Comment by ljfranklin** [comment]
@chhhavi it would simplify things for us, and I imagine other drats runners, if DRATs supported both credhub 2.0 and earlier so you didn't have to pin a specific version of drats in your pipelines. That said, we'd appreciate it if the PR submitter could make that change before merging but if that's not in the cards feel free to merge as is and someone (maybe RelEng) can make a PR to fix the issue once it becomes an issue in our pipelines.

**Comment by TisVictress** [comment]
@ljfranklin We will update the PR to support both.

**Comment by alamages** [comment]
Hello @TisVictress, any updates on this?

**Comment by athornton2012** [comment]
@alamages In order to make this PR support both permissions models in CredHub, we would essentially have to change the `credhub-test-app` to use a UAA client that was seeded with admin permissions in cf-deployment. We are in the process of discussing with relevant teams whether or not it makes sense to have a new admin client created (called the credhub_admin_client), or to use a client that is already there. @crawsible

**Pull request merged**
